### ISSUE TITLE
Конфликт параметров

### ISSUE THREAD

**Issue by soprun** [laravel-notification-channels/smsc-ru#23]
Если передать пустой параметр `login, psw, sender` значения по умолчанию будут перезаписаны на пустые.

В метод send прилетает массив параметров: 
```
Array
(
    [phones] => +78008835651
    [mes] => Код подтверждения: 92899. Используйте его, чтобы войти.
    [sender] => 
)
```

Есть `$base` который содержит базовый набор параметров, также содержит `sender`,  который берется из настроек.

При выполнении `$params = array_merge($base, $params);` где  `$params['sender'] === '' `(пустая строка) происходит смещение и базовый параметр `sender` перезаписываться на пустое значение.

Так как в `NotificationChannels\SmscRu\SmscRuMessage` свойство `$from` пустая строка, то базовое значение всегда перезаписывается на пустое, если явно не указать в массиве `$params`.

<img width="1812" alt="screen shot 2018-03-15 at 20 50 42" src="https://user-images.githubusercontent.com/2864278/37481361-95ce3e9a-2892-11e8-9b72-caa8be4cff56.png">

**Comment by jhaoda** [comment]
Исправлено #24.
