### ISSUE TITLE
Unable to return no phones from routeNotificationForSmscru

### ISSUE THREAD

**Issue by Finesse** [laravel-notification-channels/smsc-ru#26]
If I return `null`, an empty string or an empty array from the `routeNotificationForSmscru` method of a Notifiable, I get a `CouldNotSendNotification` exception. I think this is incorrect because all the built-in Laravel channels just do nothing if no recipient is set (examples: [1](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Notifications/Channels/MailChannel.php#L52), [2](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Notifications/Channels/NexmoSmsChannel.php#L47), [3](https://github.com/laravel/framework/blob/5.6/src/Illuminate/Notifications/Channels/SlackWebhookChannel.php#L40)).

To workaround it I have to do the following in my notification classes:

```php
public function via($notifiable)
{
    if ($notifiable->routeNotificationFor('smscru', $this)) {
        return [SmscRuChannel::class];
    } else {
        return [];
    }
}
```

There is one more problem. Notifications objects are not passed to the `routeNotificationForSmscru` method so I can't decide what number to send an SMS to depending on the notification class or object.

Also it would be great if I can return either a string or an array of phone numbers from `routeNotificationForSmscru` method. I know I can return multiple phones in a single string separating them by comma, but the array would be a more convenient and Laravel-style way.

If you agree, I can implement all the features and make a pull request.

**Comment by Finesse** [comment]
If the feature isn't implemented, we can workaround it (make able `routeNotificationForSmscru` to return an empty value) this way:

```php
class AccountApproved extends Notification
{
    public function via($notifiable)
    {
        if ($notifiable->routeNotificationFor('smscru', $this)) {
            return [SmscRuChannel::class];
        } else {
            return [];
        }
    }

    public function toSmscRu($notifiable)
    {
        return SmscRuMessage::create("Task #{$notifiable->id} is complete!");
    }
}
```

**Comment by jhaoda** [comment]
Thanks. I agree and I'm waiting for a PR.
