### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/smsc-ru#3]
The test seems to fail for all environment expect lowest on PHP 7.

Could you fix this?

https://travis-ci.org/laravel-notification-channels/smsc-ru/builds/152038732

**Comment by jhaoda** [comment]
PHP 7 with `COMPOSER_FLAGS="--prefer-lowest"` and PHP 5.6 with `COMPOSER_FLAGS=""`: failed on composer update.

PHP 5.6 with `COMPOSER_FLAGS="--prefer-lowest"` has issue with phpunit, fix it later.

**Comment by jhaoda** [comment]
Done.
