### ISSUE TITLE
Add phone to message object

### ISSUE THREAD

**Issue by kepka42** [laravel-notification-channels/smsc-ru#41]
It happens that you need to directly specify the recipient in the message object. (For example, a similar functionality is in the library for working with Firebase Cloud Messaging). This is necessary when we work with AnonymousNotifiable.

**Comment by jhaoda** [comment]
```php
(new AnonymousNotifiable())
    ->route('smscru', $order->getCustomerPhone())
    ->notify(new OrderArrived($order));
```
Чем не устраивает?

**Comment by kepka42** [comment]
Вариант вполне устраивает, но не в нашем случае. Мы столкнулись с проблемой, когда в момент инициации сообщения нам не известен номер телефона. Например, у нас есть только UUID пользователя, по которому можно вытащить телефон. А в момент обработки, мы можем сходить в базу и получить телефон. Под бэком я имею ввиду два разных laravel приложений.

Это кейс, когда 2 разных бэкенда со своими бд. Но только в одной лежит номер телефона. Инициация сообщения происходит из одного бэка, а обработчик запущен на втором.

Я понимаю, что такое происходит достаточно редко. В либе для FCM мы сразу решили этот вопрос, так как там было это предусмотрено.

**Comment by jhaoda** [comment]
@kepka42 не вижу в либе https://github.com/laravel-notification-channels/fcm такой возможности.

**Comment by kepka42** [comment]
@jhaoda https://github.com/benwilkins/laravel-fcm-notification в этой либе есть
