### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by faenir** [laravel-notification-channels/smsc-ru#50]
I can't update my project to Laravel 11.x and PHP 8.3 because Composer throws an error when installing "laravel-notification-channels/smsc-ru."

Could you please add support for Laravel 11?

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - illuminate/support[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.3; overridden via config.platform, actual: 8.3.10) does not satisfy that requirement.
>     - illuminate/support[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.3; overridden via config.platform, actual: 8.3.10) does not satisfy that requirement.
>     - illuminate/support[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.3; overridden via config.platform, actual: 8.3.10) does not satisfy that requirement.
>     - illuminate/support[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.3; overridden via config.platform, actual: 8.3.10) does not satisfy that requirement.
>     - Root composer.json requires laravel-notification-channels/smsc-ru ^3.4 -> satisfiable by laravel-notification-channels/smsc-ru[v3.4.0].
>     - Conclusion: don't install laravel/framework v11.20.0 (conflict analysis result)
>     - laravel-notification-channels/smsc-ru v3.4.0 requires illuminate/support 5.1 - 5.8|^6.0|^7.0|^8.0|^9.0|^10.0 -> satisfiable by illuminate/support[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev].
>     - Only one of these can be installed: illuminate/support[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev, v11.0.0, ..., 11.x-dev], laravel/framework[v11.20.0, 11.x-dev]. laravel/framework replaces illuminate/support and thus cannot coexist with it.
>     - Root composer.json requires laravel/framework ^11.20 -> satisfiable by laravel/framework[v11.20.0, 11.x-dev].

**Comment by jhaoda** [comment]
Done #52
